# Generated by Django 5.2.1 on 2025-06-04 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_loginprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='loginProfile',
            new_name='SignupData',
        ),
    ]
