# Generated by Django 5.2.1 on 2025-06-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0006_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
