# Generated by Django 5.2.1 on 2025-06-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0007_rename_user_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
