# Generated by Django 5.2.1 on 2025-06-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0011_usersuggestion_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='subject',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
