# Generated by Django 5.2.1 on 2025-06-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0012_usermessage_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeachWeddingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('package', models.CharField(max_length=100)),
                ('special_requests', models.TextField(blank=True)),
            ],
        ),
    ]
